/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adminui;

import javax.swing.JOptionPane;
import model.dao.categoryinfoDao;
import model.to.categoryinfoTo;
import utility.operations;
import utility.validate;

/**
 *
 * @author anishgarg
 */
public class addCategory extends javax.swing.JInternalFrame {

    /**
     * Creates new form addCategory
     */
    public addCategory() {
        initComponents();
    }
    public addCategory(categoryinfoTo record) {
        this();
        if(record!=null)
        {
            categoryid.setText(record.getCategoryid());
            categoryname.setText(record.getCategoryname());
            categoryid.setEditable(false);//so that our primary key can't be changed.
            btnadd.setText("Update Category Details");
            setTitle("Update Category Details");
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        categoryid = new javax.swing.JTextField();
        categoryname = new javax.swing.JTextField();
        btnadd = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Add Category Details");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Enter the CategoryID");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Enter the Categoryname");

        categoryid.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        categoryname.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        btnadd.setFont(new java.awt.Font("Malayalam MN", 2, 24)); // NOI18N
        btnadd.setText("Add Category");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(categoryname, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(136, 136, 136)
                                .addComponent(categoryid, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(btnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(categoryid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(categoryname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(btnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        // TODO add your handling code here:
        String cid= categoryid.getText().trim();
        //categoryid is the variable name of the textfield used.
        String cname= categoryname.getText().trim();
        String message="";
        if(validate.isEmpty(cid)|| validate.isEmpty(cname))
        {
            message="Plzz fill all the boxes";
        }
        else
        {
            categoryinfoTo records=new categoryinfoTo();
            records.setCategoryid(cid);
            records.setCategoryname(cname);
            categoryinfoDao actions=new categoryinfoDao();
            if(btnadd.getText().contains("Add"))
            {
            if(actions.insertRecord(records))
            {
                message="Category Details has been saved in the system";
            }
            else
            {
                message="Insertion Failure"+ actions.getErrormessage();
            }
            }
            else if(btnadd.getText().contains("Update"))
            {
                if(actions.updateRecord(records))
            {
                message="Category Details has been Updated in the system";
            }
            else
            {
                message="Update Failure"+ actions.getErrormessage();
            }
                operations.openInternalFrame(getDesktopPane(), new viewCategory());
                    dispose();
            }
            else
            {
                message="Invalid Operation Performed";
            }
            
        }
        JOptionPane.showMessageDialog(this, message);
    }//GEN-LAST:event_btnaddActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JTextField categoryid;
    private javax.swing.JTextField categoryname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
