/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adminui;

import java.util.List;
import javax.swing.JOptionPane;
import model.dao.categoryinfoDao;
import model.dao.expensesinfoDao;
import model.dao.sub_categoryinfoDao;

import model.to.categoryinfoTo;
import model.to.expensesinfoTo;
import model.to.sub_categoryinfoTo;
import utility.operations;
import utility.validate;

/**
 *
 * @author anishgarg
 */
public class addExpenses extends javax.swing.JInternalFrame {

    /**
     * Creates new form addExpenses
     */
    private int expenseid;
    public addExpenses() {
        initComponents();
        jcbsubinfo.removeAllItems();
        jcbsubinfo.addItem("Choose Any Sub_Category ID");
        List<sub_categoryinfoTo> subinfo = new sub_categoryinfoDao().getAllRecord();
        if (subinfo != null && subinfo.size() > 0) {
            for (sub_categoryinfoTo ct : subinfo) {
                jcbsubinfo.addItem(ct);
            }
        }
    }

    public addExpenses(expensesinfoTo record) {
        this();
        if (record != null) {
            jtfdescrition.setText((record.getDescription()));
            jtfamount.setText(String.valueOf(record.getAmount()));
            for (int i = 1; i < jcbsubinfo.getItemCount(); i++) {
                sub_categoryinfoTo element = (sub_categoryinfoTo) jcbsubinfo.getItemAt(i);

                if (record.getSubcategoryinfo() == (element.getSubcategoryinfo())) {
                    jcbsubinfo.setSelectedIndex(i);
                    break;
                }
            }
            //for(int i=1;i<cdpDob.)
            cdpDob.setDate(record.getExpensedate());
            //jtfsubid.setEditable(false);//so that our primary key can't be changed.
            btnexpenses.setText("Update Expenses Details");
            setTitle("Update Expenses Details");
            expenseid = record.getExpenseid();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtfamount = new javax.swing.JTextField();
        jtfdescrition = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cdpDob = new adminui.CurrentDatePanel();
        btnexpenses = new javax.swing.JButton();
        jcbsubinfo = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Add Expenses");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Enter the description");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setText("Enter the Subcategoryinfo");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setText("Enter the Amount");

        jtfamount.setFont(new java.awt.Font("Times", 1, 24)); // NOI18N

        jtfdescrition.setFont(new java.awt.Font("Times", 1, 24)); // NOI18N
        jtfdescrition.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfdescritionKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setText("Enter the ExpenseDate");

        btnexpenses.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnexpenses.setText("Add Expenses Details");
        btnexpenses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexpensesActionPerformed(evt);
            }
        });

        jcbsubinfo.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jcbsubinfo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(163, 163, 163)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtfamount)
                                    .addComponent(jtfdescrition, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                                    .addComponent(jcbsubinfo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(138, 138, 138)
                                .addComponent(cdpDob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(323, 323, 323)
                        .addComponent(btnexpenses, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(128, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jtfdescrition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jtfamount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jcbsubinfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel5)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel4)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cdpDob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(btnexpenses, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnexpensesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexpensesActionPerformed
        // TODO add your handling code here:

        // Float amount= jtfamount.getText().trim();
        String message = "";
        String description = jtfdescrition.getText().trim();
        String amount = jtfamount.getText().trim();

        boolean allvalid = true;
        if (validate.isEmpty(description)) {
            message = "Plzz fill the subcategoryID";
            allvalid = false;
        }
        if (validate.isEmpty(amount)) {
            message = "Plzz fill the sub_categoryname";
            allvalid = false;
        }
        if (jcbsubinfo.getSelectedIndex() == 0) {
            message = "plzz choose any Category ID";
            allvalid = false;
        }
        if (cdpDob.getSelectedDate() == null) {
            message += "Please Choose Valid Date Of Birth\n\n";
            allvalid = false;
        }
        if (allvalid) {
            expensesinfoTo records = new expensesinfoTo();
            sub_categoryinfoTo sub = (sub_categoryinfoTo) jcbsubinfo.getSelectedItem();
            records.setDescription((description));
            records.setAmount(Float.parseFloat(amount));
            records.setExpensedate(cdpDob.getSelectedDate());
            records.setSubcategoryinfo(sub.getSubcategoryinfo());
            expensesinfoDao actions = new expensesinfoDao();
            if (btnexpenses.getText().contains("Add")) {
                if (actions.insertRecord(records)) {
                    message = "Expenses Details has been saved in the system";
                } else {
                    message = "Insertion Failure" + actions.getErrormessage();
                }
            } else if (btnexpenses.getText().contains("Update")) {
                records.setExpenseid(expenseid);
                if (actions.updateRecord(records)) {
                    message = "Expenses Details has been Updated in the system";
                } else {
                    message = "Update Failure" + actions.getErrormessage();
                }
                operations.openInternalFrame(getDesktopPane(), new viewExpenses());
                dispose();
            } else {
                message = "Invalid Operation Performed";
            }
        }

        JOptionPane.showMessageDialog(this, message);

    }//GEN-LAST:event_btnexpensesActionPerformed

    private void jtfdescritionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfdescritionKeyTyped
        // TODO add your handling code here:
        if (!Character.isLetter(evt.getKeyChar())) {
            if (!Character.isWhitespace(evt.getKeyChar())) {
                evt.consume();
            }

        }

    }//GEN-LAST:event_jtfdescritionKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnexpenses;
    private adminui.CurrentDatePanel cdpDob;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JComboBox<Object> jcbsubinfo;
    private javax.swing.JTextField jtfamount;
    private javax.swing.JTextField jtfdescrition;
    // End of variables declaration//GEN-END:variables
}
