/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adminui;

import java.awt.Image;
import java.beans.PropertyVetoException;
import javax.swing.ImageIcon;
import model.dao.dataConnection;

/**
 *
 * @author anishgarg
 */
public class adminMainScreen extends javax.swing.JFrame {

    /**
     * Creates new form adminMainScreen
     */
    public adminMainScreen() {
        try
        {
          Image iconimage;
          iconimage=new ImageIcon(getClass().getResource("/adminui/fav.png")).getImage();
            setIconImage(iconimage);
          
        }catch(Exception ex)
        {
            System.out.println(ex);
        }
        initComponents();
        setSize(1100,640);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktoppane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        addcategory = new javax.swing.JMenuItem();
        viewcategory = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        addsubcategory = new javax.swing.JMenuItem();
        viewsubcategory = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        addexpenses = new javax.swing.JMenuItem();
        viewexpenses = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("IMS:: Admin Zone");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().add(desktoppane, java.awt.BorderLayout.CENTER);

        jMenu3.setText("category operations");
        jMenu3.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N

        addcategory.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        addcategory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminui/add.png"))); // NOI18N
        addcategory.setText("Add new Category");
        addcategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addcategoryActionPerformed(evt);
            }
        });
        jMenu3.add(addcategory);

        viewcategory.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        viewcategory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminui/view.png"))); // NOI18N
        viewcategory.setText("View Category details");
        viewcategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewcategoryActionPerformed(evt);
            }
        });
        jMenu3.add(viewcategory);

        jMenuBar1.add(jMenu3);

        jMenu1.setText("sub_categoryinfo operations");
        jMenu1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N

        addsubcategory.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        addsubcategory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminui/add.png"))); // NOI18N
        addsubcategory.setText("Add New SubCategory");
        addsubcategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addsubcategoryActionPerformed(evt);
            }
        });
        jMenu1.add(addsubcategory);

        viewsubcategory.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        viewsubcategory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminui/view.png"))); // NOI18N
        viewsubcategory.setText("View SubCategory Details");
        viewsubcategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewsubcategoryActionPerformed(evt);
            }
        });
        jMenu1.add(viewsubcategory);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("expensesinfo operations");
        jMenu2.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N

        addexpenses.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        addexpenses.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminui/add.png"))); // NOI18N
        addexpenses.setText("Add Expenses");
        addexpenses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addexpensesActionPerformed(evt);
            }
        });
        jMenu2.add(addexpenses);

        viewexpenses.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        viewexpenses.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminui/view.png"))); // NOI18N
        viewexpenses.setText("View Expenses Details");
        viewexpenses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewexpensesActionPerformed(evt);
            }
        });
        jMenu2.add(viewexpenses);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        dataConnection.closeConnection();
    }//GEN-LAST:event_formWindowClosing

    private void addcategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addcategoryActionPerformed
        // TODO add your handling code here:
        addCategory ac=new addCategory();
        ac.setVisible(true);
        desktoppane.add(ac);
        try// THIS IS BECAUSE IF THE OPEN A INTERNAL FRAME THAN AGAIN OPEN THE ANOTHER INTERNAL 
            //FRAME THEN THE 2 FRAME HIDES BEHIND THE 1 FRAME 
            //SO NOT TO HIDE WE USE GETSELECTED() ANFD IT THROWS EXCEPTION ALSO
        {
           ac.setSelected(true);
        }catch(PropertyVetoException ex)
        {
            System.out.println(ex);
        }
    }//GEN-LAST:event_addcategoryActionPerformed

    private void viewcategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewcategoryActionPerformed
        // TODO add your handling code here:
        viewCategory vc=new viewCategory();
        vc.setVisible(true);
        desktoppane.add(vc);
          try// THIS IS BECAUSE IF THE OPEN A INTERNAL FRAME THAN AGAIN OPEN THE ANOTHER INTERNAL 
            //FRAME THEN THE 2 FRAME HIDES BEHIND THE 1 FRAME 
            //SO NOT TO HIDE WE USE GETSELECTED() ANFD IT THROWS EXCEPTION ALSO
        {
           vc.setSelected(true);
        }catch(PropertyVetoException ex)
        {
            System.out.println(ex);
        }
    }//GEN-LAST:event_viewcategoryActionPerformed

    private void addsubcategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addsubcategoryActionPerformed
        // TODO add your handling code here:
        addsubCategory asc=new addsubCategory();
        asc.setVisible(true);
        desktoppane.add(asc);
          try// THIS IS BECAUSE IF THE OPEN A INTERNAL FRAME THAN AGAIN OPEN THE ANOTHER INTERNAL 
            //FRAME THEN THE 2 FRAME HIDES BEHIND THE 1 FRAME 
            //SO NOT TO HIDE WE USE GETSELECTED() ANFD IT THROWS EXCEPTION ALSO
        {
           asc.setSelected(true);
        }catch(PropertyVetoException ex)
        {
            System.out.println(ex);
        }
    }//GEN-LAST:event_addsubcategoryActionPerformed

    private void addexpensesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addexpensesActionPerformed
        // TODO add your handling code here:
        addExpenses ae=new addExpenses();
        ae.setVisible(true);
        desktoppane.add(ae);
          try// THIS IS BECAUSE IF THE OPEN A INTERNAL FRAME THAN AGAIN OPEN THE ANOTHER INTERNAL 
            //FRAME THEN THE 2 FRAME HIDES BEHIND THE 1 FRAME 
            //SO NOT TO HIDE WE USE GETSELECTED() ANFD IT THROWS EXCEPTION ALSO
        {
           ae.setSelected(true);
        }catch(PropertyVetoException ex)
        {
            System.out.println(ex);
        }
    }//GEN-LAST:event_addexpensesActionPerformed

    private void viewsubcategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewsubcategoryActionPerformed
        // TODO add your handling code here:
        viewSubCategory vsc=new viewSubCategory();
        vsc.setVisible(true);
        desktoppane.add(vsc);
          try// THIS IS BECAUSE IF THE OPEN A INTERNAL FRAME THAN AGAIN OPEN THE ANOTHER INTERNAL 
            //FRAME THEN THE 2 FRAME HIDES BEHIND THE 1 FRAME 
            //SO NOT TO HIDE WE USE GETSELECTED() ANFD IT THROWS EXCEPTION ALSO
        {
           vsc.setSelected(true);
        }catch(PropertyVetoException ex)
        {
            System.out.println(ex);
        }
    }//GEN-LAST:event_viewsubcategoryActionPerformed

    private void viewexpensesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewexpensesActionPerformed
        // TODO add your handling code here:
         viewExpenses ve=new viewExpenses();
        ve.setVisible(true);
        desktoppane.add(ve);
          try// THIS IS BECAUSE IF THE OPEN A INTERNAL FRAME THAN AGAIN OPEN THE ANOTHER INTERNAL 
            //FRAME THEN THE 2 FRAME HIDES BEHIND THE 1 FRAME 
            //SO NOT TO HIDE WE USE GETSELECTED() ANFD IT THROWS EXCEPTION ALSO
        {
           ve.setSelected(true);
        }catch(PropertyVetoException ex)
        {
            System.out.println(ex);
        }
    }//GEN-LAST:event_viewexpensesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminMainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminMainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminMainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminMainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminMainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addcategory;
    private javax.swing.JMenuItem addexpenses;
    private javax.swing.JMenuItem addsubcategory;
    private javax.swing.JDesktopPane desktoppane;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem viewcategory;
    private javax.swing.JMenuItem viewexpenses;
    private javax.swing.JMenuItem viewsubcategory;
    // End of variables declaration//GEN-END:variables
}
