/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adminui;

import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.table.DefaultTableModel;
import model.dao.expensesinfoDao;
import model.to.expensesinfoTo;
import utility.operations;

/**
 *
 * @author anishgarg
 */
public class viewExpenses extends javax.swing.JInternalFrame {

    /**
     * Creates new form viewExpenses
     */
    private List<expensesinfoTo> expense;
    private JPopupMenu popup;
    private int srow;//this 

    public viewExpenses() {
        initComponents();
        bindTables();
        srow = -1;
        popup = new JPopupMenu();
        JMenuItem deleteitem = new JMenuItem("Delete Record");
        deleteitem.setFont(new Font("Arial", Font.BOLD, 20));
        JMenuItem edititem = new JMenuItem("Edit Record");
        edititem.setFont(new Font("Arial", Font.BOLD, 20));
        try {
            ImageIcon icon;
            icon = new ImageIcon(getClass().getResource("/adminui/delete.png"));
            deleteitem.setIcon(icon);
        } catch (Exception ex) {
        }
        try {
            ImageIcon icon;
            icon = new ImageIcon(getClass().getResource("/adminui/edit.png"));
            edititem.setIcon(icon);
        } catch (Exception ex) {
        }
        popup.add(deleteitem);
        popup.add(edititem);
        deleteitem.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                deleteRecord();
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        });
        edititem.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                editRecord();
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        });
    }

    private void deleteRecord() {
        if (srow != -1 && expense != null && srow < expense.size()) {
            int result = JOptionPane.showConfirmDialog(this, "Are You Sure To Removed This Reccord?", "Message From System", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
            if (result == JOptionPane.YES_OPTION) {
                expensesinfoTo ct = expense.get(srow);
                expensesinfoDao action = new expensesinfoDao();
                String message = "";
                if (action.deleteRecord(ct.getExpenseid())) {
                    message = "Record is Removed From Database";
                    bindTables();
                } else {
                    message = "Record does not Remove From Database Due To : " + action.getErrormessage();
                }
                JOptionPane.showMessageDialog(this, message);
            }
        }
        srow = -1;
    }

    private void editRecord() {
        if (srow != -1 && expense != null && srow < expense.size()) {
            expensesinfoTo ct = expense.get(srow);
            operations.openInternalFrame(getDesktopPane(), new addExpenses(ct));
            dispose();
        }
    }

    public void bindTables() {
        String[] col_list = {"expenseid", "description", "amount", "subcategoryinfo", "expensedate"};
        expense = new expensesinfoDao().getAllRecord();
        Object[][] records = null;
        if (expense != null && expense.size() > 0) {
            // to allocae the memory of the records
            records = new Object[expense.size()][col_list.length];
            int i = 0;
            for (expensesinfoTo cc : expense) {
                records[i] = new Object[]{cc.getExpenseid(), cc.getDescription(), cc.getAmount(), cc.getSubcategoryinfo(), cc.getExpensedate()};
                i++;
            }
        } else {
            records = new Object[1][col_list.length];
            records[0] = new Object[]{"no records", "no records"};
        }
        DefaultTableModel modal = new DefaultTableModel(records, col_list);
        tableexpenses.setModel(modal);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableexpenses = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("View Expenses");

        tableexpenses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableexpenses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableexpensesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableexpenses);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 748, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableexpensesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableexpensesMouseClicked
        // TODO add your handling code here:
        if (evt.getButton() == MouseEvent.BUTTON3)//Button3 is for mouse right click
        {
            int point = tableexpenses.rowAtPoint(evt.getPoint());//givw at what point click occurs
            tableexpenses.getSelectionModel().setSelectionInterval(point, point);// it will hightlight the column on which u wull do right click.
            srow = tableexpenses.getSelectedRow();
            popup.show(tableexpenses, getX(), getY());

        }
    }//GEN-LAST:event_tableexpensesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableexpenses;
    // End of variables declaration//GEN-END:variables
}
