/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adminui;

import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.table.DefaultTableModel;
import model.dao.sub_categoryinfoDao;
import model.to.sub_categoryinfoTo;
import utility.operations;

/**
 *
 * @author anishgarg
 */
public class viewSubCategory extends javax.swing.JInternalFrame {

    /**
     * Creates new form viewSubCategory
     */
    private List<sub_categoryinfoTo> subcategory;
    private JPopupMenu popup;
    private int srow;//this variable represent the selected row.
    public viewSubCategory() {
        initComponents();
        bindtables();
        srow=-1;
        popup = new JPopupMenu();
        JMenuItem deleteitem = new JMenuItem("Delete Record");
        deleteitem.setFont(new Font("Arial", Font.BOLD, 20));
        JMenuItem edititem = new JMenuItem("Edit Record");
        edititem.setFont(new Font("Arial", Font.BOLD, 20  ));
        try {
            ImageIcon icon;
            icon = new ImageIcon(getClass().getResource("/adminui/delete.png"));
            deleteitem.setIcon(icon);
        } catch (Exception ex) {
        }
        try {
            ImageIcon icon;
            icon = new ImageIcon(getClass().getResource("/adminui/edit.png"));
            edititem.setIcon(icon);
        } catch (Exception ex) {
        }
        popup.add(deleteitem);
        popup.add(edititem);
        deleteitem.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                deleteRecord();
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        });
         edititem.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                editRecord();
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        });
    }
    
     private void deleteRecord()
    {
        if(srow!=-1 && subcategory!=null && srow<subcategory.size())
        {
             int result = JOptionPane.showConfirmDialog(this, "Are You Sure To Removed This Reccord?", "Message From System", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
            if (result == JOptionPane.YES_OPTION) {
                sub_categoryinfoTo ct = subcategory.get(srow);
                sub_categoryinfoDao action = new sub_categoryinfoDao();
                String message = "";
                if (action.deleteRecord(ct.getSubcategoryinfo())) {
                    message = "Record is Removed From Database";
                    bindtables();
                } else {
                    message = "Record does not Remove From Database Due To : " + action.getErrormessage();
                }
                JOptionPane.showMessageDialog(this, message);
            }
        }
        srow=-1;
    }
    private void editRecord()
    {
        if(srow!=-1 && subcategory!=null && srow<subcategory.size())
        {
            sub_categoryinfoTo ct = subcategory.get(srow);
            operations.openInternalFrame(getDesktopPane(), new addsubCategory(ct));
            dispose();
        }
    }
    
    public void bindtables()
    {
         String[] col_list={"subcategoryinfo","subcategoryname","categoryid"};
         subcategory=new sub_categoryinfoDao().getAllRecord();
         Object[][] records=null;
         if(subcategory!=null &&subcategory.size()>0)
         {
             // to allocae the memory of the records
             records=new Object[subcategory.size()][col_list.length];
             int i=0;
             for(sub_categoryinfoTo cc: subcategory)
             {
                records[i]=new Object[]{cc.getSubcategoryinfo(),cc.getSubcategoryname(),cc.getCategoryid()};
                i++;
             }
         }
         else
         {
             records=new Object[1][col_list.length];
             records[0]=new Object[]{"no records","no records"};
         }
         DefaultTableModel modal=new DefaultTableModel(records,col_list);
         tablesubcategory.setModel(modal);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablesubcategory = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("View SubCategory");

        tablesubcategory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablesubcategory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablesubcategoryMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablesubcategory);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 669, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 77, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablesubcategoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablesubcategoryMouseClicked
          // TODO add your handling code here:
          if(evt.getButton()==MouseEvent.BUTTON3)//Button3 is for mouse right click
        {
            int point = tablesubcategory.rowAtPoint(evt.getPoint());//givw at what point click occurs
            tablesubcategory.getSelectionModel().setSelectionInterval(point, point);// it will hightlight the column on which u wull do right click.
            srow=tablesubcategory.getSelectedRow();
            popup.show(tablesubcategory,getX(),getY());
            
            
        }
    }//GEN-LAST:event_tablesubcategoryMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablesubcategory;
    // End of variables declaration//GEN-END:variables
}
